site_name: <PROJECT_NAME>

markdown_extensions:
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search

theme:
  name: material
  custom_dir: docs/overrides
  logo: docs/img/pgedge-logo-light.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.prune
    - navigation.top
    - toc.follow

copyright: Copyright &copy; <COPYRIGHT_RANGE> pgEdge, Inc

repo_url: https://github.com/<GITHUB_REPO>

nav:
  - Getting Started: index.md
  - Changelog: changelog.md
