{{- if not .Values.initialAdmin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-admin" (include "<BINARY_NAME>.fullname" .) }}
  labels: {{- include "<BINARY_NAME>.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  password: {{ randAlphaNum 32 | b64enc }}
{{- end }}
