name: CI - Docs

on:
    push:
        branches: [main]
        paths:
            - 'docs/**'
            - 'mkdocs.yml'
            - '.github/workflows/ci-docs.yml'
    pull_request:
        branches: [main]
        paths:
            - 'docs/**'
            - 'mkdocs.yml'
            - '.github/workflows/ci-docs.yml'

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: '3.12'
            - name: Install MkDocs
              run: pip install mkdocs-material mkdocs-redoc-tag
            - name: Build docs
              run: mkdocs build --strict
